package com.bizwink.search.persistence;

import com.bizwink.search.domain.Letter;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

public interface LetterMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_LETTER
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_LETTER
     *
     * @mbggenerated
     */
    int insert(Letter letter);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_LETTER
     *
     * @mbggenerated
     */
    int insertSelective(Letter letter);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_LETTER
     *
     * @mbggenerated
     */
    Letter selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_LETTER
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Letter letter);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_LETTER
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Letter letter);

    List<Letter> getDepartment();

    List<Letter> getCategory();

    Letter getLetter(Map<String, Object> param);

    int countLetterList(Map<String, Object> param);

    List<Letter> getLetterList(Map<String, Object> param);
}